- name: This playbook is to achive catlaogue service installtion and comm to mongodb
  hosts: catalogue
  become: true
  tasks:
  - name: Setup NodeJS repos
    ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

  - name: This task is to Install NodeJS
    ansible.builtin.yum:
      name: nodejs
      state: latest
  
  - name: check roboshop user
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true
  
  - name: Print output
    ansible.builtin.debug:
      msg: "{{out}}"

  
