- name: This playbook is to install mongodb on the mongodb host 
  hosts: mongodb
  become: true 
  tasks:
  - name: This task is to copy the custom mongo repo 
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: This task is to Install MongoDB
    ansible.builtin.yum:
      name: mongodb-org
      state: latest
  
  - name: Replace Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/mongod.conf
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Restart service mongod, in all cases
    ansible.builtin.service:
      name: mongod
      state: restarted
      enabled: yes
  

