- name: This playbook is to install mongodb on the mongodb host 
  hosts: mongodb
  become: true 
  tasks:
  - name: This task is to copy the custom mongo repo 
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo